// Generated by CoffeeScript 1.6.2
require.config({
  paths: {
    zepto: "./lib/zepto",
    domReady: "./lib/require.domReady",
    cs: "./lib/require.cs",
    "coffee-script": "./lib/coffee-script",
    chai: "./lib/chai",
    sinon: "./lib/sinon",
    mocha: "./lib/mocha"
  },
  shim: {
    zepto: {
      exports: "$"
    },
    sinon: {
      exports: "sinon"
    }
  },
  waitSeconds: 180,
  baseUrl: "/",
  urlArgs: (function() {
    return new Date().getTime();
  })()
});

require(["chai", "sinon", "mocha"], function(chai, sinon) {
  mocha.setup("bdd");
  console.log("hoge");
  require(["./test/helper"], function() {
    console.log("hoge");
    return mocha.run();
  });
});
