// Generated by CoffeeScript 1.6.2
require.config({
  waitSeconds: 180,
  baseUrl: "/",
  urlArgs: (function() {
    return new Date().getTime();
  })()
});

require(["src/helper", "src/flickable"], function(Helper, Flickable) {
  var div, flickable;

  div = document.createElement("div");
  console.log(Helper);
  console.log(Flickable);
  return flickable = new Flickable(div, {});
});
