// Generated by CoffeeScript 1.6.2
/*
  Flickable.js - based on flipsnap.js (http://pxgrid.github.com/js-flipsnap/)
  
  Author:  @yuya
  Version: 0.1
*/
(function(root, factory) {
  if (typeof define === "function" && define.amd === "object") {
    return define(NS, [], function() {
      factory(root, root.document);
      return root[NS];
    });
  } else {
    return factory(root, root.document);
  }
})(this, function(global, document) {
  var NS;

  NS = "Flickable";
  return global[NS] = {};
});
