// Generated by CoffeeScript 1.6.2
(function(root, factory) {
  if (typeof define === "function" && define.amd === "object") {
    return define(NS, [], function() {
      factory(root, root.document);
      return root[NS];
    });
  } else {
    return factory(root, root.document);
  }
})(this, function(global, document) {
  var NS;

  NS = "Flickable";
  return global[NS] = {};
});
